acclist/urls.py
from django.urls import path

from . import views

app_name = 'acclist'
urlpatterns = [
    path('', views.index, name='index'),

    # account list
    path('<str:fmt>/<str:username>/', views.alllist, name='alllist'),
    path('<str:fmt>/<str:username>/mail/<int:mailid>/', views.maillinkedlist, name='maillinkedlist'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/', views.servicelinkedlist, name='servicelinkedlist'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/', views.addresslinkedlist, name='addresslinkedlist'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/', views.phonenumlinkedlist, name='phonenumlinkedlist'),

    # actions against account linked informations
    path('<str:fmt>/<str:username>/mail/<int:mailid>/deleteform/', views.maildeleteconfirm, name='maildeleteconfirm'),
    path('<str:fmt>/<str:username>/mail/<int:mailid>/delete/', views.maildelete, name='maildelete'),
    path('<str:fmt>/<str:username>/mail/none/deletesuccess/', views.maildeletesuccess, name='maildeletesuccess'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/deleteform/', views.servicedeleteconfirm, name='servicedeleteconfirm'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/delete/', views.servicedelete, name='servicedelete'),
    path('<str:fmt>/<str:username>/service/none/deletesuccess/', views.servicedeletesuccess, name='servicedeletesuccess'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/deleteform/', views.addressdeleteconfirm, name='addressdeleteconfirm'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/delete/', views.addressdelete, name='addressdelete'),
    path('<str:fmt>/<str:username>/address/none/deletesuccess/', views.addressdeletesuccess, name='addressdeletesuccess'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/deleteform/', views.phonenumdeleteconfirm, name='phonenumdeleteconfirm'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/delete/', views.phonenumdelete, name='phonenumdelete'),
    path('<str:fmt>/<str:username>/phonenum/none/deletesuccess/', views.phonenumdeletesuccess, name='phonenumdeletesuccess'),
 
    # account detail
    path('<str:fmt>/<str:username>/account/<int:accid>/', views.accdetail, name='accdetail'),

    # account update
    path('<str:fmt>/<str:username>/account/<int:accid>/updateform/', views.updateform, name='accupdateform'),
    path('<str:fmt>/<str:username>/account/<int:accid>/update/', views.update, name='accupdate'),
    path('<str:fmt>/<str:username>/account/<int:accid>/updatesuccess/', views.updatesuccess, name='accupdatesuccess'),

    # account insert
    path('<str:fmt>/<str:username>/account/new/', views.insertform, name='accinsertform'),
    path('<str:fmt>/<str:username>/account/new/insert/', views.insert, name='accinsert'),
    path('<str:fmt>/<str:username>/account/<int:accid>/insertsuccess/', views.insertsuccess, name='accinsertsuccess'),

    # accountdelete
    path('<str:fmt>/<str:username>/account/<int:accid>/deleteform/', views.deleteconfirm, name='accdeleteconfirm'),
    path('<str:fmt>/<str:username>/account/<int:accid>/delete/', views.delete, name='accdelete'),
    path('<str:fmt>/<str:username>/account/none/deletesuccess/', views.deletesuccess, name='accdeletesuccess'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:fmt>/', views.index, name='fmt'),
    path('html/login/', views.login, name='login'),
    path('html/redirect/', views.login_redirect, name='loginredirect'),
    path('html/logout/', views.logout, name='logout'),
    path('<str:fmt>/update/<str:username>/form/', views.account_update_form, name='update_form'),
    path('<str:fmt>/update/<str:username>/', views.account_update, name='update'),
    path('<str:fmt>/update/<str:username>/success/', views.account_updatesuccess, name='update_success'),
    path('<str:fmt>/create/form/', views.account_create_form, name='create_form'),
    path('<str:fmt>/create/', views.account_create, name='create'),
    path('<str:fmt>/create/success/', views.account_createsuccess, name='create_success'),
]

accup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import login as django_login

from accounts import views as accounts_view

urlpatterns = [
    path('', django_login,
        {'template_name': 'accounts/login.html'}),
    path('accounts/', include('accounts.urls')),
    path('acclist/', include('acclist.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# user management data
class User(models.Model):
    status = models.SmallIntegerField(default=1)
    accup_user_name = models.CharField(max_length=40, unique=True)
    cipherkey = models.CharField(max_length=100)
    createdate = models.DateTimeField(auto_now_add=True)
    modifieddate = models.DateTimeField(auto_now=True)
    deletedate = models.DateTimeField(blank=True, null=True)

# login history
class Userlogin(models.Model):
    accup_user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    login_date = models.DateTimeField(auto_now_add=True)
    login_ip = models.GenericIPAddressField()

accounts/views.py
from django.conf import settings
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.template import loader
from django.urls import reverse
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout as django_logout
from django.contrib.auth.views import login as django_login
from django.contrib.auth.models import User as Djguser
from django.db.models import Q
from django.db import IntegrityError, transaction

from .permissions import is_users_url
from .renders import *
from .models import User as Accuser
from .models import Userlogin as Ulin
from .lib.form.signupform import *
from .lib.definitions.message import *
from .lib.definitions.message_error_update import *
from .lib.exception.accountsexception import AccountsException
from .lib.logic.update import update_accuser
from acclist.lib.logic.cryptoutil import encrypt_pass_cookie

import sys

login_url_def_name = 'accounts:login'

@login_required(login_url=login_url_def_name)
def login_redirect(request, fmt='html'):
    return HttpResponseRedirect(
        reverse(
            'acclist:alllist',
            args=(fmt, request.user.username)))

def login(request, fmt='html'):
    if "username" in request.POST and "password" in request.POST:
        un = request.POST["username"]
        pw = request.POST["password"]
        key = un
        val = encrypt_pass_cookie(pw)
        response = django_login(request, template_name='accounts/login.html')
        response.set_signed_cookie(key, val,
            salt=settings.COOKIE_SIGNED_SALT,
            max_age=settings.COOKIE_MAXAGE,
            secure=settings.COOKIE_SECURE,
            httponly=True)
        # insert login history
        ulin = Ulin()
        ulin.accup_user_id = get_object_or_404(
            Accuser, Q(accup_user_name=un))
        ulin.login_ip = request.META.get('REMOTE_ADDR')
        ulin.save()
    else:
        response = django_login(request, template_name='accounts/login.html')
    return response

def logout(request, fmt='html'):
    return django_logout(request, template_name='accounts/logout.html')

def index(request, fmt='html'):
    return login_redirect(request, fmt)

def update_view_main(request, fmt, username=None):
    # main process
    if fmt == 'html':
        if username is None:
            params = SignupForm(request.POST)
        else:
            params = UpdateForm(request.POST)
    else:
        raise Http404
    if not params.is_valid():
        if fmt == 'html':
            if username is None:
                result = UPDATE_RESPONSE['create_parameter_error']
            else:
                result = UPDATE_RESPONSE['update_parameter_error']
            return signup_form_render(
                request, username,
                newuser=(username is None),
                relay={'result': result},
                validate=params)
    if username is None:
        accuser = None
        djguser = None
    else:
        accuser = get_object_or_404(Accuser,
            Q(accup_user_name=username))
        djguser = get_object_or_404(Djguser,
            Q(username=username))
    # update
    result = None
    acc = None
    try:
        with transaction.atomic():
            acc = update_accuser(accuser, djguser, params)
        result = UPDATE_RESPONSE['ok']
    except IntegrityError as e:
        print(sys.exc_info())
        result = UPDATE_RESPONSE['transaction_error']
    except AccountsException as e:
        result = e.accounts_err_dict
    except Exception as e:
        result = UPDATE_RESPONSE['unexpected_error']
        print(sys.exc_info())
        # for test, raise it again
        raise e

    if fmt == 'html':
        # failure case
        if result['code'] != 0:
            return signup_form_render(
                request, username, newuser=(username is None),
                relay={'result': result})
        # success
        if username is None:
            return HttpResponseRedirect(
                reverse('accounts:create_success', kwargs={'fmt': fmt}))
        else:
            return HttpResponseRedirect(
                reverse('accounts:update_success',
                    kwargs={'fmt': fmt, 'username': username}))

@login_required(login_url=login_url_def_name)
def account_update_form(request, username, fmt):
    # permission check
    is_users_url(request.user, username)

    # main process
    return HttpResponse(
        signup_form_render(request, username))

@login_required(login_url=login_url_def_name)
def account_update(request, fmt, username=None):
    # permission check
    is_users_url(request.user, username)

    # main view logic
    return update_view_main(request, fmt, username)

def account_create_form(request, fmt):
    return HttpResponse(
        signup_form_render(request, None, True))

def account_create(request, fmt):
    # main view logic
    return update_view_main(request, fmt, None)

def account_updatesuccess(request, username, fmt):
    # main process
    template = loader.get_template('accounts/updatesuccess.html')
    context = {
        'message': RESPONSE_MESSAGE['update_success'],
        'username': username,
    }
    return HttpResponse(template.render(context, request))

def account_createsuccess(request, fmt):
    # main process
    template = loader.get_template('accounts/createsuccess.html')
    context = {
        'message': RESPONSE_MESSAGE['create_success'],
    }
    return HttpResponse(template.render(context, request))

accounts/templates/accounts/createsuccess.html
{% extends "base.html" %}

{% block contents %}

{% if message %}
<div class="container">
  <div class="row justify-content-center">
    <div class="alert alert-info col-4 mt-3 mb-3" role="alert">
      {{ message }}
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-4">
      <button type="button" class="btn btn-link w-100" onclick="location.href='{% url 'accounts:login' %}'">Login</button>
    </div>
  </div>
</div>
{% else %}
<div class="container">
  <div class="row justify-content-center">
    <div class="alert alert-danger col-4 mt-3 mb-3" role="alert">
      不明なエラーが発生しました。
    </div>
  </div>
</div>
{% endif %}

{% endblock contents %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block contents %}

<div class="container">
  <form action="{% url 'accounts:login' %}" method="post" role="form">
    <div class="row justify-content-center">
      <h3 class="col-4 py-3 text-center">Acc-Up Login</h3>
    </div>
    {% if form.errors  %}
    <div class="row justify-content-center">
      <div class="alert alert-danger col-4 mt-3 mb-5" role="alert">
        Your username and password didn't match. Please try again.
      </div>
    </div>
    {% endif %}
    <div class="row justify-content-center">
      {% csrf_token %}
      <div class="form-group col-4">
        <input class="form-control" id="id_username" name="username" type="text" value="" maxlength="256" placeholder="Username" aria-describedby="sizing-addon1" autofocus required/>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="form-group col-4">
        <input class="form-control" id="id_password" name="password" type="password" value="" maxlength="256" placeholder="Pasword" aria-describedby="sizing-addon1" required/>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-4 text-center">
        <a href="{% url 'accounts:login' %}">Forgot password</a>
      </div>
      <input name="next" type="hidden" value="{{ next }}"/>
    </div>
    <div class="row justify-content-center mt-5">
      <div class="col-4">
        <button type="submit" class="btn btn-primary w-100">Login</button>
      </div>
    </div>
  </form>
  <div class="row justify-content-center">
    <div class="col-4 py-3">
      <button type="button" class="btn btn-default w-100" onclick="location.href='{% url 'accounts:create_form' 'html' %}'">Sign-Up</button>
    </div>
  </div>
</div>
{% endblock contents %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% block contents %}

<div class="container">
  <div class="row justify-content-center">
    <div class="alert alert-info col-4 mt-3 mb-3" role="alert">
      ログアウトしました。
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-4">
      <button type="button" class="btn btn-link w-100" onclick="location.href='{% url 'accounts:login' %}'">Login again</button>
    </div>
  </div>
</div>

{% endblock contents %}

accounts/templates/accounts/signup_form.html
{% extends "base.html" %}
{% block contents %}
    <div class="container">
    {% if newuser or username and email %}
        <div class="row justify-content-center">
            <div class="col-12 py-3 text-center">
                <h1 class="page_title">{{ title_text }}</h1>
            </div>
        </div>

        {% if validate %}
        <div class="row justify-content-center">
            <div class="col-4 py-3 text-center">
                <div class="validate">
                    {{ validate.non_field_errors }}
                </div>
            </div>
        </div>
        {% endif %}

        {% if relay %}
        <div class="row justify-content-center">
            <div class="col-4 py-3 text-center">
                <div class="error">
                    <div class="error_message">
                        {{ relay.result.message }}
                    </div>
                    <div class="error_detail">
            {% for d in relay.result.py_e %}
                        <div class="msg">{{ d }}</div>
            {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        {% if newuser %}
        <form action="{% url 'accounts:create' 'html' %}" method="post">
        {% else %}
        <form action="{% url 'accounts:update' 'html' username %}" method="post">
        {% endif %}

        {% csrf_token %}

        {% if newuser %}
            <div class="row justify-content-center">
                <div class="form-group col-4">
                    <label for="username">{{ key_string.username }}</label>
                    <input id="userid" name="userid" type="text" class="form-control">
            {% if validate.userid.errors %}
                    <small class="form-text text-muted">
                        {{ validate.userid.errors }}
                    </small>
            {% endif %}
                </div>
            </div>
        {% else %}
            <div class="row justify-content-center">
                <div class="form-group col-4">
                    <label>{{ key_string.password }}</label>
                    <div class="form-row">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="updatepwd" id="updatepwd1" value="1" onclick="$('#collapse_password_form').collapse('show')">
                            <label class="form-check-label" for="updatepwd1">{{ key_string.password_update }}</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="updatepwd" id="updatepwd0" value="0" onclick="$('#collapse_password_form').collapse('hide')" checked>
                            <label class="form-check-label" for="updatepwd0">{{ key_string.password_not_update }}</label>
                        </div>
                    </div>
            {% if validate.updatepwd.errors %}
                    <small class="form-text text-muted">
                        {{ validate.updatepwd.errors }}
                    </small>
            {% endif %}
                </div>
            </div>
        {% endif %}

        {% if not newuser %}
            <div class="collapse" id="collapse_password_form">
        {% else %}
            <div>
        {% endif %}
                <div class="row justify-content-center">
                    <div class="form-group col-4">
                        <label for="password">{{ key_string.password }}</label>
                        <input id="password" name="password" type="password" class="form-control">
        {% if validate.password.errors %}
                        <small class="form-text text-muted">
                            {{ validate.password.errors }}
                        </small>
        {% endif %}
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="form-group col-4">
                        <label for="password_confirm">{{ key_string.password_confirm }}</label>
                        <input id="password_confirm" name="password_confirm" type="password" class="form-control">
        {% if validate.password_confirm.errors %}
                        <small class="form-text text-muted">
                            {{ validate.password_confirm.errors }}
                        </small>
        {% endif %}
                    </div>
                </div>
            </div>

            <div class="row justify-content-center my-3">
                <div class="form-group col-4">
                    <label for="email">{{ key_string.email }}</label>
                    <input id="email" name="email" type="text" class="form-control">
        {% if validate.email.errors %}
                    <small class="form-text text-muted">
                        {{ validate.email.errors }}
                    </small>
        {% endif %}
                </div>
            </div>

        {% if not newuser %}
            <div class="row justify-content-center my-3">
                <div class="form-group col-4">
                    <label for="current_password">{{ key_string.password_old }}</label>
                    <input id="current_password" name="current_password" type="password" class="form-control">
            {% if validate.current_password.errors %}
                    <small class="form-text text-muted">
                        {{ validate.current_password.errors }}
                    </small>
            {% endif %}
                </div>
            </div>
        {% endif %}

            <div class="row justify-content-center">
                <div class="form-group col-4">
        {% if newuser %}
                    <input type="submit" value="Sign up" class="btn btn-info w-100">
        {% else %}
                    <input type="submit" value="Update" class="btn btn-info w-100">
        {% endif %}
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="form-group col-4">
        {% if newuser %}    
                    <button type="button" class="btn btn-secondary w-100" onclick="location.href='{% url 'accounts:index' %}'">Cancel</button>
        {% else %}
                    <button type="button" class="btn btn-secondary w-100" onclick="location.href='{% url 'acclist:alllist' 'html' username %}'">Cancel</button>
        {% endif %}
                </div>
            </div>
        </form>
    {% else %}
        <p class="no_content_message">Failed to load account data.</p>
    {% endif %}
    </div>
{% endblock contents %}

accounts/templates/accounts/updatesuccess.html
{% extends "base.html" %}

{% block contents %}

{% if message and username %}
<div class="container">
  <div class="row justify-content-center">
    <div class="alert alert-info col-4 mt-3 mb-3" role="alert">
      {{ message }}
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-4">
      <button type="button" class="btn btn-link w-100" onclick="location.href='{% url 'acclist:alllist' 'html' username %}'">View your accounts list</button>
    </div>
  </div>
</div>
{% else %}
<div class="container">
  <div class="row justify-content-center">
    <div class="alert alert-danger col-4 mt-3 mb-3" role="alert">
      不明なエラーが発生しました。
    </div>
  </div>
</div>
{% endif %}

{% endblock contents %}