acclist/urls.py
from django.urls import path

from . import views

app_name = 'acclist'
urlpatterns = [
    path('', views.index, name='index'),

    # account list
    path('<str:fmt>/<str:username>/', views.alllist, name='alllist'),
    path('<str:fmt>/<str:username>/mail/<int:mailid>/', views.maillinkedlist, name='maillinkedlist'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/', views.servicelinkedlist, name='servicelinkedlist'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/', views.addresslinkedlist, name='addresslinkedlist'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/', views.phonenumlinkedlist, name='phonenumlinkedlist'),

    # actions against account linked informations
    path('<str:fmt>/<str:username>/mail/<int:mailid>/deleteform/', views.maildeleteconfirm, name='maildeleteconfirm'),
    path('<str:fmt>/<str:username>/mail/<int:mailid>/delete/', views.maildelete, name='maildelete'),
    path('<str:fmt>/<str:username>/mail/none/deletesuccess/', views.maildeletesuccess, name='maildeletesuccess'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/deleteform/', views.servicedeleteconfirm, name='servicedeleteconfirm'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/delete/', views.servicedelete, name='servicedelete'),
    path('<str:fmt>/<str:username>/service/none/deletesuccess/', views.servicedeletesuccess, name='servicedeletesuccess'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/deleteform/', views.addressdeleteconfirm, name='addressdeleteconfirm'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/delete/', views.addressdelete, name='addressdelete'),
    path('<str:fmt>/<str:username>/address/none/deletesuccess/', views.addressdeletesuccess, name='addressdeletesuccess'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/deleteform/', views.phonenumdeleteconfirm, name='phonenumdeleteconfirm'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/delete/', views.phonenumdelete, name='phonenumdelete'),
    path('<str:fmt>/<str:username>/phonenum/none/deletesuccess/', views.phonenumdeletesuccess, name='phonenumdeletesuccess'),
 
    # account detail
    path('<str:fmt>/<str:username>/account/<int:accid>/', views.accdetail, name='accdetail'),

    # account update
    path('<str:fmt>/<str:username>/account/<int:accid>/updateform/', views.updateform, name='accupdateform'),
    path('<str:fmt>/<str:username>/account/<int:accid>/update/', views.update, name='accupdate'),
    path('<str:fmt>/<str:username>/account/<int:accid>/updatesuccess/', views.updatesuccess, name='accupdatesuccess'),

    # account insert
    path('<str:fmt>/<str:username>/account/new/', views.insertform, name='accinsertform'),
    path('<str:fmt>/<str:username>/account/new/insert/', views.insert, name='accinsert'),
    path('<str:fmt>/<str:username>/account/<int:accid>/insertsuccess/', views.insertsuccess, name='accinsertsuccess'),

    # accountdelete
    path('<str:fmt>/<str:username>/account/<int:accid>/deleteform/', views.deleteconfirm, name='accdeleteconfirm'),
    path('<str:fmt>/<str:username>/account/<int:accid>/delete/', views.delete, name='accdelete'),
    path('<str:fmt>/<str:username>/account/none/deletesuccess/', views.deletesuccess, name='accdeletesuccess'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:fmt>/', views.index, name='fmt'),
    path('html/login/', views.login, name='login'),
    path('html/redirect/', views.login_redirect, name='loginredirect'),
    path('html/logout/', views.logout, name='logout'),
    path('<str:fmt>/update/<str:username>/form/', views.account_update_form, name='update_form'),
    path('<str:fmt>/update/<str:username>/', views.account_update, name='update'),
    path('<str:fmt>/update/<str:username>/success/', views.account_updatesuccess, name='update_success'),
    path('<str:fmt>/create/form/', views.account_create_form, name='create_form'),
    path('<str:fmt>/create/', views.account_create, name='create'),
    path('<str:fmt>/create/success/', views.account_createsuccess, name='create_success'),
]

accup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import login as django_login

from accounts import views as accounts_view

urlpatterns = [
    path('', django_login,
        {'template_name': 'accounts/login.html'}),
    path('accounts/', include('accounts.urls')),
    path('acclist/', include('acclist.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ STATIC_URL }}favicon.ico">

    <title>
        Acc-Up - 
{% if title_text %}
        {{ title_text }}
{% else %}
        unknown page
{% endif %}
    </title>
    <!-- <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body style="padding-top: 90px;">

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'accounts:index' %}">Acc-Up</a>
        {% if username %}
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="myaccsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Accounts
              </a>
              <div class="dropdown-menu" aria-labelledby="Dropdown">
                <a class="dropdown-item" href="{% url 'acclist:alllist' 'html' username %}">Account list</a>
                <a class="dropdown-item" href="{% url 'acclist:accinsertform' 'html' username %}">Add another account</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:update_form' 'html' username %}">My Acc-Up account</a>
            </li>
          </ul>
        </div>
        <div class="my-2 my-lg-0">
          <span class="navbar-text mr-3">
            Hi, {{ username }}.
          </span>
          <button type="button" class="btn btn-secondary" onclick="location.href='{% url 'accounts:logout' %}'">Logout</button>
        </div>
        {% endif %}
      </div>
    </nav>

    <div class="container">
    {% block contents %}{% endblock contents %}
    </div>


  </body>
</html>