acclist/urls.py
from django.urls import path

from . import views

app_name = 'acclist'
urlpatterns = [
    path('', views.index, name='index'),

    # account list
    path('<str:fmt>/<str:username>/', views.alllist, name='alllist'),
    path('<str:fmt>/<str:username>/mail/<int:mailid>/', views.maillinkedlist, name='maillinkedlist'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/', views.servicelinkedlist, name='servicelinkedlist'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/', views.addresslinkedlist, name='addresslinkedlist'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/', views.phonenumlinkedlist, name='phonenumlinkedlist'),

    # actions against account linked informations
    path('<str:fmt>/<str:username>/mail/<int:mailid>/deleteform/', views.maildeleteconfirm, name='maildeleteconfirm'),
    path('<str:fmt>/<str:username>/mail/<int:mailid>/delete/', views.maildelete, name='maildelete'),
    path('<str:fmt>/<str:username>/mail/none/deletesuccess/', views.maildeletesuccess, name='maildeletesuccess'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/deleteform/', views.servicedeleteconfirm, name='servicedeleteconfirm'),
    path('<str:fmt>/<str:username>/service/<int:serviceid>/delete/', views.servicedelete, name='servicedelete'),
    path('<str:fmt>/<str:username>/service/none/deletesuccess/', views.servicedeletesuccess, name='servicedeletesuccess'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/deleteform/', views.addressdeleteconfirm, name='addressdeleteconfirm'),
    path('<str:fmt>/<str:username>/address/<int:addressid>/delete/', views.addressdelete, name='addressdelete'),
    path('<str:fmt>/<str:username>/address/none/deletesuccess/', views.addressdeletesuccess, name='addressdeletesuccess'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/deleteform/', views.phonenumdeleteconfirm, name='phonenumdeleteconfirm'),
    path('<str:fmt>/<str:username>/phonenum/<int:phonenumid>/delete/', views.phonenumdelete, name='phonenumdelete'),
    path('<str:fmt>/<str:username>/phonenum/none/deletesuccess/', views.phonenumdeletesuccess, name='phonenumdeletesuccess'),
 
    # account detail
    path('<str:fmt>/<str:username>/account/<int:accid>/', views.accdetail, name='accdetail'),

    # account update
    path('<str:fmt>/<str:username>/account/<int:accid>/updateform/', views.updateform, name='accupdateform'),
    path('<str:fmt>/<str:username>/account/<int:accid>/update/', views.update, name='accupdate'),
    path('<str:fmt>/<str:username>/account/<int:accid>/updatesuccess/', views.updatesuccess, name='accupdatesuccess'),

    # account insert
    path('<str:fmt>/<str:username>/account/new/', views.insertform, name='accinsertform'),
    path('<str:fmt>/<str:username>/account/new/insert/', views.insert, name='accinsert'),
    path('<str:fmt>/<str:username>/account/<int:accid>/insertsuccess/', views.insertsuccess, name='accinsertsuccess'),

    # accountdelete
    path('<str:fmt>/<str:username>/account/<int:accid>/deleteform/', views.deleteconfirm, name='accdeleteconfirm'),
    path('<str:fmt>/<str:username>/account/<int:accid>/delete/', views.delete, name='accdelete'),
    path('<str:fmt>/<str:username>/account/none/deletesuccess/', views.deletesuccess, name='accdeletesuccess'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:fmt>/', views.index, name='fmt'),
    path('html/login/', views.login, name='login'),
    path('html/redirect/', views.login_redirect, name='loginredirect'),
    path('html/logout/', views.logout, name='logout'),
    path('<str:fmt>/update/<str:username>/form/', views.account_update_form, name='update_form'),
    path('<str:fmt>/update/<str:username>/', views.account_update, name='update'),
    path('<str:fmt>/update/<str:username>/success/', views.account_updatesuccess, name='update_success'),
    path('<str:fmt>/create/form/', views.account_create_form, name='create_form'),
    path('<str:fmt>/create/', views.account_create, name='create'),
    path('<str:fmt>/create/success/', views.account_createsuccess, name='create_success'),
]

accup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import login as django_login

from accounts import views as accounts_view

urlpatterns = [
    path('', django_login,
        {'template_name': 'accounts/login.html'}),
    path('accounts/', include('accounts.urls')),
    path('acclist/', include('acclist.urls')),
    path('admin/', admin.site.urls),
]

acclist/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, Http404
from django.db.models import Q
from django.shortcuts import get_object_or_404
# from django.views import generic
#from django.views.decorators.http import require_http_methods
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db import IntegrityError, transaction
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout as django_logout
from django.core.signing import BadSignature, SignatureExpired

from accounts.models import User as Acclistuser
from accounts.permissions import is_users_url
from accounts.views import login_redirect
from accounts.views import logout as acc_logout
from .renders import *
from .models import *
import json
from .lib.definitions.common import *
from .lib.definitions.valuename import *
from .lib.definitions.message import *
from .lib.definitions.message_error_update import *
from .lib.definitions.specialconsts import *
#from .lib.logic.util import *
from .lib.exception.acclistexception import *
from .lib.exception.acccryptoexception import AcccryptoDecryptException
from .lib.form.update import *
from .lib.logic.update import *
from .lib.logic.cryptoutil import get_encryptor
from .lib.logic.modelutil import *

import sys


login_url_def_name = 'accounts:login'

#
# view functions
#

@login_required(login_url=login_url_def_name)
def index(request):
    return login_redirect(request)

def failure(request):
    return django_logout(request, template_name='acclist/failure.html')

@login_required(login_url=login_url_def_name)
def alllist(request, username, fmt):
    # permission check
    is_users_url(request.user, username)

    # prepare decryption
    user = get_object_or_404(Acclistuser, Q(accup_user_name=username))
    try:
        enc = get_encryptor(request, user)
    except (KeyError, BadSignature, SignatureExpired):
        return failure(request)
    except AcccryptoDecryptException as e:
        #return failure(request)
        raise e

    # prepare lists (decryption and sort)
    mail_list = Mailaddr.objects.filter(
        accup_user_id__accup_user_name=username)
    mail_list = obj_sort_by_property_name(
        obj_list_decrypt(mail_list, enc), 'mailaddr_text')
    address_list = Address.objects.filter(
        accup_user_id__accup_user_name=username)
    address_list = obj_sort_by_property_name(
        obj_list_decrypt(address_list, enc), 'address_text')
    phonenum_list = Phonenum.objects.filter(
        accup_user_id__accup_user_name=username)
    phonenum_list = obj_sort_by_property_name(
        obj_list_decrypt(phonenum_list, enc), 'phonenum_text')
    service_list = Service.objects.filter(
        accup_user_id__accup_user_name=username)
    service_list = obj_sort_by_property_name(
        obj_list_decrypt(service_list, enc), 'service_name')
    account_list = Account.objects.filter(
        accup_user_id__accup_user_name=username)
    account_list = obj_sort_by_lambda(
        obj_list_decrypt(account_list, enc), lambda x:x.service.service_name)

    # set view arguments
    template = loader.get_template('acclist/accandmaillist.html')
    context = {
        'title_text': 'Account list',
        'account_list': account_list,
        'mail_list': mail_list,
        'address_list': address_list,
        'phonenum_list': phonenum_list,
        'service_list': service_list,
        'username': username,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url=login_url_def_name)
def accdetail(request, username, accid, fmt, relay=None, rendered=None):
    # permission check
    is_users_url(request.user, username)

    # prepare decryption
    user = get_object_or_404(Acclistuser, Q(accup_user_name=username))
    try:
        enc = get_encryptor(request, user)
    except (KeyError, BadSignature, SignatureExpired):
        return failure(request)
    except AcccryptoDecryptException as e:
        #return failure(request)
        raise e

    # main process
    account = get_object_or_404(Account,
        Q(accup_user_id__accup_user_name=username),
        Q(id=accid))

    return HttpResponse(
        accdetail_render(
            request, username, account.decrypt(enc), relay, rendered))

@login_required(login_url=login_url_def_name)
def servicelinkedlist(request, username, serviceid, fmt, relay=None):
    # permission check
    is_users_url(request.user, username)

    # prepare decryption
    user = get_object_or_404(Acclistuser, Q(accup_user_name=username))
    try:
        enc = get_encryptor(request, user)
    except (KeyError, BadSignature, SignatureExpired):
        return failure(request)
    except AcccryptoDecryptException as e:
        #return failure(request)
        raise e

    # main process
    service_obj = get_object_or_404(Service,
        Q(accup_user_id__accup_user_name=username),
        Q(id=serviceid))

    return HttpResponse(servicelinkedlist_render(
        request, service_obj.decrypt(enc), enc, username, relay))

@login_required(login_url=login_url_def_name)
def servicedeleteconfirm(request, username, serviceid, fmt):
    # permission check
    is_users_url(request.user, username)

    # prepare decryption
    user = get_object_or_404(Acclistuser, Q(accup_user_name=username))
    try:
        enc = get_encryptor(request, user)
    except (KeyError, BadSignature, SignatureExpired):
        return failure(request)
    except AcccryptoDecryptException as e:
        #return failure(request)
        raise e

    # main process
    # get account object
    service = get_object_or_404(Service,
        Q(accup_user_id__accup_user_name=username),
        Q(id=serviceid))
    # related accounts
    linked_tmp = Account.objects.filter(
        Q(service__id=service.id),
        Q(accup_user_id__accup_user_name=username))
    #decrypt
    service.decrypt(enc)
    related_account_list = obj_sort_by_lambda(
        obj_list_decrypt(linked_tmp, enc),
        lambda x:x.service.service_name)
    # delete information
    msg_template = loader.get_template('acclist/linkedinfodeleteconfirm.html')
    msg_context = {
        'info_id': service.id,
        'info_delete_url_key': 'acclist:servicedelete',
        'kind_of_info_text': KIND_OF_INFO_TEXT['service'],
        'target_info': service.service_name,
        'related_acounts': (None if len(related_account_list) == 0 else related_account_list),
        'username': username,
    }
    relay = msg_template.render(msg_context, request)
    # response
    template = loader.get_template('acclist/acclist.html')
    context = {
        'rendered': relay,
        'description': DESCRIPTION_MESSAGE['servicelinkedlist'],
        'key_value': service.service_name,
        'count': len(related_account_list),
        'account_list': related_account_list,
        'username': username,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url=login_url_def_name)
def servicedelete(request, username, serviceid, fmt):
    # permission check
    is_users_url(request.user, username)

    # prepare decryption
    user = get_object_or_404(Acclistuser, Q(accup_user_name=username))
    try:
        enc = get_encryptor(request, user)
    except (KeyError, BadSignature, SignatureExpired):
        return failure(request)
    except AcccryptoDecryptException as e:
        #return failure(request)
        raise e

    # main process
    service = get_object_or_404(Service,
        Q(accup_user_id__accup_user_name=username),
        Q(id=serviceid))
    # delete account record
    result = None
    try:
        with transaction.atomic():
            service.delete()
        result = LINKED_INFO_DELETE_RESPONSE['ok']
    except IntegrityError as e:
        print(sys.exc_info())
        result = LINKED_INFO_DELETE_RESPONSE['transaction_error']
    except Exception as e:
        print(sys.exc_info())
        result = LINKED_INFO_DELETE_RESPONSE['unexpected_error']
        # for test, raise it again
        raise e

    # return response
    if fmt == 'html':
        if result['code'] != 0:
            errmsg = loader.get_template('acclist/linkedinfoerrormsg.html')
            context = {
                'relay': result['message'],
            }
            return servicelinkedlist_render(
                request, service.decrypt(enc), enc, username,
                relay=errmsg.render(context, request))
        else:
            return HttpResponseRedirect(
                reverse('acclist:servicedeletesuccess', args=(fmt, username)))
    # only html format request is allowed, at least for now..
    #elif fmt == 'json':
    #    return HttpResponseRedirect(
    #        reverse('acclist:accdetail', args=
    #            (fmt, username, accid,)))

@login_required(login_url=login_url_def_name)
def servicedeletesuccess(request, username, fmt):
    # permission check
    is_users_url(request.user, username)

    # main process
    template = loader.get_template('acclist/linkedinfodeletesuccess.html')
    context = {
        'title_text': 'Service has been deleted.',
        'message': RESPONSE_MESSAGE['service_delete_success'],
        'username': username,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url=login_url_def_name)
def maillinkedlist(request, username, mailid, fmt, relay=None):
    # permission check
    is_users_url(request.user, username)

    # prepare decryption
    user = get_object_or_404(Acclistuser, Q(accup_user_name=username))
    try:
        enc = get_encryptor(request, user)
    except (KeyError, BadSignature, SignatureExpired):
        return failure(request)
    except AcccryptoDecryptException as e:
        #return failure(request)
        raise e

    # main process
    mailaddr_obj = get_object_or_404(Mailaddr,
        Q(accup_user_id__accup_user_name=username),
        Q(id=mailid))

acclist/templates/acclist/accandmaillist.html
{% extends "base.html" %}
{% block contents %}
    <h1 class="page_title">Account List</h1>
    {% if account_list %}
    <table class="table table-striped">
        <tbody>
        {% for acc in account_list %}
            <tr class="row">
                <td class="col-10" style="vertical-align: middle;"><a href="{% url 'acclist:accdetail' 'html' username acc.id %}">
                    {{ acc.service.service_name }} - {{ acc.name }}
                </a></td>
                <td class="col-2" style="text-align: right;">
                    <button type="button" class="btn btn-info" onclick="location.href='{% url 'acclist:accupdateform' 'html' username acc.id %}'">
                        編集
                    </button>
                    <button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:accdeleteconfirm' 'html' username acc.id %}'">
                        削除
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="no_content_message">No accounts are registered.</p>
    {% endif %}

    <h1 class="page_title">Mail Address List</h1>
    {% if mail_list %}
    <table class="table table-striped">
        <tbody>
        {% for mail in mail_list %}
            <tr class="row">
                <td class="col-10" style="vertical-align: middle;"><a href="{% url 'acclist:maillinkedlist' 'html' username mail.id %}">
                    {{ mail.mailaddr_text }}
                </a></td>
                <td class="col-2" style="text-align: right;"><button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:maildeleteconfirm' 'html' username mail.id %}'">
                    削除
                </button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="no_content_message">No mail addresses are registered.</p>
    {% endif %}

    <h1 class="page_title">Address List</h1>
    {% if address_list %}
    <table class="table table-striped">
        <tbody>
        {% for addr in address_list %}
            <tr class="row">
                <td class="col-10" style="vertical-align: middle;"><a href="{% url 'acclist:addresslinkedlist' 'html' username addr.id %}">
                    {{ addr.address_text }}
                </a></td>
                <td class="col-2" style="text-align: right;"><button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:addressdeleteconfirm' 'html' username addr.id %}'">
                    削除
                </button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="no_content_message">No addresses are registered.</p>
    {% endif %}

    <h1 class="page_title">Phonenum List</h1>
    {% if phonenum_list %}
    <table class="table table-striped">
        <tbody>
        {% for pn in phonenum_list %}
            <tr class="row">
                <td class="col-10" style="vertical-align: middle;"><a href="{% url 'acclist:phonenumlinkedlist' 'html' username pn.id %}">
                    {{ pn.phonenum_text }}
                </a></td>
                <td class="col-2" style="text-align: right;"><button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:phonenumdeleteconfirm' 'html' username pn.id %}'">
                    削除
                </button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="no_content_message">No phonenums are registered.</p>
    {% endif %}

    <h1 class="page_title">Service List</h1>
    {% if service_list %}
    <table class="table table-striped">
        <tbody>
        {% for svc in service_list %}
            <tr class="row">
                <td class="col-10" style="vertical-align: middle;"><a href="{% url 'acclist:servicelinkedlist' 'html' username svc.id %}">
                    {{ svc.service_name }}
                </a></td>
                <td class="col-2" style="text-align: right;"><button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:servicedeleteconfirm' 'html' username svc.id %}'">
                    削除
                </button></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="no_content_message">No services are registered.</p>
    {% endif %}

{% endblock contents %}

acclist/templates/acclist/accdetail.html
{% extends "base.html" %}
{% block contents %}
    {% if title_text %}
    <h1 class="page_title">{{ title_text }}</h1>
    {% endif %}
    {% if relay %}
    <div class="error">
        <div class="error_message">
        {{ relay.result.message }}
        </div>
        <div class="error_detail">
        {% for d in relay.result.py_e %}
            <div class="msg">{{ d }}</div>
        {% endfor %}
        </div>
    </div>
    {% endif %}
    {% if rendered %}
        {{ rendered }}
    {% endif %}
    {% if message %}
    <div class="message">
        {{ message }}
    </div>
    {% endif %}
    {% if account %}
        {% if not delete %}
    <p class="button_set">
        <button type="button" class="btn btn-info" onclick="location.href='{% url 'acclist:accupdateform' 'html' account.accup_user_id.accup_user_name account.id %}'">update account</button>
        <button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:accdeleteconfirm' 'html' account.accup_user_id.accup_user_name account.id %}'">delete account</button>
    </p>
        {% endif %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>item</th>
                <th>value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="listed_object">{{ key_string.status }}</td>
                <td class="listed_object">{{ account.status }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.service }}</td>
                <td class="listed_object">{{ account.service.service_name }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.name }}</td>
                <td class="listed_object">{{ account.name }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.password }}</td>
                <td class="listed_object">{{ account.passwd }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.mailaddr1 }}</td>
                <td class="listed_object">{{ account.mailaddr1.mailaddr_text }}</td>
            <tr>
                <td class="listed_object">{{ key_string.mailaddr2 }}</td>
                <td class="listed_object">{{ account.mailaddr2.mailaddr_text }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.mailaddr3 }}</td>
                <td class="listed_object">{{ account.mailaddr3.mailaddr_text }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.address }}</td>
                <td class="listed_object">{{ account.address.address_text }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.phonenum }}</td>
                <td class="listed_object">{{ account.phonenum.phonenum_text }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.acclink1 }}</td>
                <td class="listed_object">
        {% if account.link1_id %}
                    <a href="{% url 'acclist:accdetail' 'html' account.accup_user_id.accup_user_name account.link1_id %}">{{ account.link1.service.service_name }} - {{ account.link1.name }}</a>
        {% endif %}
                </td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.acclink2 }}</td>
                <td class="listed_object">
        {% if account.link2_id %}
                    <a href="{% url 'acclist:accdetail' 'html' account.accup_user_id.accup_user_name account.link2_id %}">{{ account.link2.service.service_name }} - {{ account.link2.name }}</a>
        {% endif %}
                </td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.acclink3 }}</td>
                <td class="listed_object">
        {% if account.link3_id %}
                    <a href="{% url 'acclist:accdetail' 'html' account.accup_user_id.accup_user_name account.link3_id %}">{{ account.link3.service.service_name }} - {{ account.link3.name }}</a>
        {% endif %}
                </td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.multitype }}</td>
                <td class="listed_object">{{ account.multifactorauth_type }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.multiinfo }}</td>
                <td class="listed_object">{{ account.multifactorauth_id }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.secretq1 }}</td>
                <td class="listed_object">{{ account.secret_q1 }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.secreta1 }}</td>
                <td class="listed_object">{{ account.secret_a1 }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.secretq2 }}</td>
                <td class="listed_object">{{ account.secret_q2 }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.secreta2 }}</td>
                <td class="listed_object">{{ account.secret_a2 }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.secretq3 }}</td>
                <td class="listed_object">{{ account.secret_q3 }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.secreta3 }}</td>
                <td class="listed_object">{{ account.secret_a3 }}</td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.registerdate }}</td>
                <td class="listed_object">
        {% if account.account_register_date %}
                    {{ account.account_register_date }}
        {% endif %}
                </td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.unregisterdate }}</td>
                <td class="listed_object">
        {% if account.account_unregister_date %}
                    {{ account.account_unregister_date }}
        {% endif %}
                </td>
            </tr>
            <tr>
                <td class="listed_object">{{ key_string.memo }}</td>
                <td class="listed_object">{{ account.memo }}</td>
            </tr>
            <tr>
                <td class="listed_object">(id)</td>
                <td class="listed_object">{{ account.id }}</td>
            </tr>
            <tr>
                <td class="listed_object">({{ key_string.accupid }})</td>
                <td class="listed_object">{{ account.accup_user_id.accup_user_name }}</td>
            </tr>
            <tr>
                <td class="listed_object">(createdate)</td>
                <td class="listed_object">{{ account.createdate }}</td>
            </tr>
            <tr>
                <td class="listed_object">(modifieddate)</td>
                <td class="listed_object">{{ account.modifieddate }}</td>
            </tr>
            <tr>
                <td class="listed_object">(deletedate)</td>
                <td class="listed_object">{{ account.deletedate }}</td>
            </tr>
        </tbody>
    </table>
        {% if not delete %}
    <p class="button_set">
        <button type="button" class="btn btn-info" onclick="location.href='{% url 'acclist:accupdateform' 'html' account.accup_user_id.accup_user_name account.id %}'">update account</button>
        <button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:accdeleteconfirm' 'html' account.accup_user_id.accup_user_name account.id %}'">delete account</button>
    </p>
        {% endif %}
    {% else %}
    <p class="no_content_message">The account does not exist.</p>
    {% endif %}
    <button type="button" class="btn btn-link" onclick="location.href='{% url 'acclist:alllist' 'html' username %}'">Go back to account list</button>
{% endblock contents %}

acclist/templates/acclist/acclist.html
{% extends "base.html" %}
{% block contents %}
    <h1 class="page_title">Account list</h1>
    {% if rendered %}
        {{ rendered }}
    {% endif %}
    <p class="description">{{ description|safe }}{{ key_value }}</p>
    <p class="count">
        Listed account(s): {{ count }}
    </p>
    {% if account_list %}
    <table class="table table-striped">
        <tbody>
        {% for acc in account_list %}
            <tr class="row">
                <td class="col-10" style="vertical-align: middle;"><a href="{% url 'acclist:accdetail' 'html' username acc.id %}">
                    {{ acc.service.service_name }} - {{ acc.name }}
                </a></td>
                <td class="col-2" style="text-align: right;">
                    <button type="button" class="btn btn-info" onclick="location.href='{% url 'acclist:accupdateform' 'html' username acc.id %}'">
                        編集
                    </button>
                    <button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:accdeleteconfirm' 'html' username acc.id %}'">
                    削除
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="no_content_message">No accounts are listed.</p>
    {% endif %}
    <button type="button" class="btn btn-link" onclick="location.href='{% url 'acclist:alllist' 'html' username %}'">Go back to account list</button>
{% endblock contents %}

acclist/templates/acclist/deleteconfirm.html
        <p class="deleteconfirm_message">
            サービス {{ service }} のアカウント {{ accname }} の情報を削除します。<br>
{% if related_acounts %}
            このアカウントは、以下のアカウントにリンクされています。<br>
            <ul>
    {% for acc in related_acounts %}
        <li><a href="{% url 'acclist:accdetail' 'html' username acc.id %}">
            {{ acc.service.service_name }} - {{ acc.name }}
        </a></li>
    {% endfor %}
            </ul>
            これらの他のアカウントとのリンク情報も削除されます。<br>
{% endif %}
            削除した情報は復元できません。削除してよろしいですか？
        </p>
        <p class="deleteconfirm_button">
            <button type="button" class="btn btn-danger" onclick="location.href='{% url 'acclist:accdelete' 'html' username accid %}'">
                はい、削除します
            </button>
            <button type="button" class="btn btn-default" onclick="location.href='{% url 'acclist:accdetail' 'html' username accid %}'">
                いいえ、削除しません
            </button>
        </p>

acclist/templates/acclist/deletesuccess.html
{% extends "base.html" %}
{% block contents %}
    <h1 class="page_title">{{ title_text }}</h1>
    {% if message %}
        {{ message }}
    {% endif %}
    <a href="{% url 'acclist:alllist' 'html' username %}">Go back to account list</a>
{% endblock contents %}

acclist/templates/acclist/linkedinfodeletesuccess.html
{% extends "base.html" %}
{% block contents %}
    <h1 class="page_title">{{ title_text }}</h1>
    {% if message %}
    <p class="message">
        {{ message }}
    </p>
    {% endif %}
    <a href="{% url 'acclist:alllist' 'html' username %}">Go back to account list</a>
{% endblock contents %}